"""Feedback generation (FR-6.10).

Feedback is **template-driven**, assembled from the computed metrics, not
generated by a language model. Three reasons (08-nlp-architecture.md §6):

1. It is deterministic and reproducible, which an academic evaluation requires.
2. It cannot hallucinate praise for vocabulary the student did not use.
3. It needs no external API, keeping the system self-contained and free to run.

The tone rules are product requirements, not style preferences. The hammer tier
in particular must never read as humiliating: it always opens with the same
encouragement and always names something the student did do.
"""

from __future__ import annotations

from typing import Any

from app.models.enums import Gender, GraphType, RewardTier
from app.nlp.detector import DetectionResult
from app.nlp.scoring import ScoreBreakdown
from app.nlp.terms import CompiledTargets, TargetTerm
from app.nlp.writing import (
    OVERLONG_FLOOR,
    SENTENCE_LENGTH_MIN,
    WritingQuality,
)

#: The fixed encouragement the lowest tier must always carry.
#:
#: Specified verbatim by the product requirements and asserted by a test. A
#: student who scored below 50% is the one most likely to stop using the
#: platform, so the words they see are not left to a template's mood.
HAMMER_ENCOURAGEMENT = "Keep Practicing! You Can Improve!"

TIER_HEADLINES: dict[RewardTier, str] = {
    RewardTier.CROWN: "Graph Champion",
    RewardTier.FLOWER: "Rising Writer",
    RewardTier.STEADY: "Steady Learner",
    RewardTier.HAMMER: "Keep Practicing!",
}

#: The crown headline is gendered, matching the avatar system's framing.
GENDERED_CROWN_HEADLINES: dict[Gender, str] = {
    Gender.MALE: "Graph King",
    Gender.FEMALE: "Graph Queen",
}

#: What to attempt next, by tier.
NEXT_STEP_BY_TIER: dict[RewardTier, str] = {
    RewardTier.CROWN: (
        "Try a harder graph, or the same chart type with a tighter word limit — "
        "you have the vocabulary, so the challenge now is precision."
    ),
    RewardTier.FLOWER: (
        "Attempt another graph of this type and aim to work in the two or three "
        "terms you missed."
    ),
    RewardTier.STEADY: (
        "Read the target vocabulary list for this graph, then try describing the "
        "same chart again using three terms you did not use the first time."
    ),
    RewardTier.HAMMER: (
        "Open the vocabulary library, pick three words from it, and write a short "
        "description of this same graph using all three. Small steps count."
    ),
}

#: How many suggestions to give at once.
#:
#: A student handed nine corrections acts on none of them. Three is what fits
#: on a results card and what a person can hold in mind for the next attempt.
MAX_STRENGTHS = 4
MAX_IMPROVEMENTS = 3

#: Of those, how many may be vocabulary suggestions.
#:
#: Without a quota, a weak answer generates so many missing-category
#: suggestions that they fill every slot and the writing advice is never seen —
#: so the students who most need to be told to open with an overview are
#: precisely the ones never told. Any unused writing slots go back to
#: vocabulary, which is still 70% of the score.
MAX_VOCABULARY_IMPROVEMENTS = 2

#: Component score above which a writing measure is called a strength, and
#: below which it becomes a suggestion.
STRENGTH_THRESHOLD = 75.0
WEAKNESS_THRESHOLD = 50.0


def generate(
    *,
    detection: DetectionResult,
    writing: WritingQuality,
    score: ScoreBreakdown,
    targets: CompiledTargets,
    graph_type: GraphType | None = None,
    gender: Gender | None = None,
    target_min: int,
    target_max: int,
) -> dict[str, Any]:
    """Build the feedback object stored on the score."""
    tier = score.reward_tier
    strengths = _strengths(detection, writing, score)
    improvements = _merge_improvements(
        _vocabulary_improvements(detection),
        _writing_improvements(writing, target_min, target_max),
    )

    return {
        "headline": _headline(tier, gender),
        "message": _message(tier, score, targets),
        "strengths": strengths[:MAX_STRENGTHS],
        "improvements": improvements,
        "missing_by_category": _missing_by_category(detection),
        "next_step": _next_step(tier, graph_type),
    }


def _headline(tier: RewardTier, gender: Gender | None) -> str:
    if tier is RewardTier.CROWN and gender is not None:
        return GENDERED_CROWN_HEADLINES.get(gender, TIER_HEADLINES[tier])
    return TIER_HEADLINES[tier]


def _message(tier: RewardTier, score: ScoreBreakdown, targets: CompiledTargets) -> str:
    used = score.unique_detected_count
    total = score.total_target_count
    tally = f"You used {used} of the {total} target terms for this graph."

    if tier is RewardTier.HAMMER:
        # The encouragement leads, before any number. A student reading a low
        # score first has often stopped reading by the time the support arrives.
        return f"{HAMMER_ENCOURAGEMENT} {tally}"

    opening = {
        RewardTier.CROWN: "Outstanding.",
        RewardTier.FLOWER: "Strong work.",
        RewardTier.STEADY: "A solid attempt.",
    }[tier]

    if score.bonus_terms_used:
        plural = "s" if score.bonus_terms_used > 1 else ""
        tally += (
            f" You also reached for {score.bonus_terms_used} bonus term{plural} "
            "beyond the required list."
        )
    return f"{opening} {tally}"


def _strengths(
    detection: DetectionResult, writing: WritingQuality, score: ScoreBreakdown
) -> list[str]:
    """Things the student actually did. Never empty.

    Every branch here reports something measured. Nothing is invented, which is
    the whole reason feedback is templated rather than generated — but the
    final fallback guarantees that even an answer that scored zero on every
    measure gets an honest, non-hollow sentence rather than an empty list.
    """
    strengths: list[str] = []

    by_category: dict[str, tuple[str, list[str]]] = {}
    for entry in detection.detected:
        code = entry.term.category_code
        name, forms = by_category.setdefault(code, (entry.term.category_name, []))
        forms.extend(entry.matched_forms)

    for name, forms in sorted(by_category.values(), key=lambda pair: -len(pair[1])):
        if len(forms) >= 2:
            strengths.append(f"Good range of {name.lower()} language: {', '.join(forms[:4])}")

    if writing.has_overview and writing.overview_score >= STRENGTH_THRESHOLD:
        strengths.append("Clear overview statement near the start")
    if writing.word_count_score >= STRENGTH_THRESHOLD:
        strengths.append(f"Well-judged length at {writing.word_count} words")
    if writing.sentence_structure_score >= STRENGTH_THRESHOLD:
        strengths.append("Varied sentence structure with subordinate clauses")
    if writing.lexical_diversity_score >= STRENGTH_THRESHOLD:
        strengths.append("Wide vocabulary range across the whole answer")

    if not strengths and detection.detected:
        first = detection.detected[0]
        strengths.append(f"You reached for target vocabulary: {first.matched_forms[0]}")
    if not strengths:
        strengths.append(
            f"You wrote {writing.word_count} words and made a start — "
            "that is what practice is for"
        )

    _ = score  # kept in the signature so every generator reads the same inputs
    return strengths


def _merge_improvements(vocabulary: list[str], writing: list[str]) -> list[str]:
    """Combine both kinds of suggestion under the per-kind quota."""
    merged = vocabulary[:MAX_VOCABULARY_IMPROVEMENTS]
    merged += writing[: MAX_IMPROVEMENTS - len(merged)]
    if len(merged) < MAX_IMPROVEMENTS:
        merged += [line for line in vocabulary if line not in merged][
            : MAX_IMPROVEMENTS - len(merged)
        ]
    return merged


def _vocabulary_improvements(detection: DetectionResult) -> list[str]:
    """Suggestions naming the specific words to try next."""
    improvements: list[str] = []

    for name, terms, already_used in _missing_grouped(detection):
        words = " or ".join(f"'{t.term}'" for t in terms[:2])
        if already_used:
            # The student did use this category, just not these words. Saying
            # "no comparison language yet" here would tell them they failed to
            # do something they demonstrably did — the fastest way to lose a
            # learner's trust in the feedback.
            improvements.append(
                f"Widen the {name.lower()} language — {words} would add precision "
                "alongside what you already used"
            )
        else:
            improvements.append(
                f"No {name.lower()} language yet — {words} would describe that part precisely"
            )

    return improvements


def _writing_improvements(writing: WritingQuality, target_min: int, target_max: int) -> list[str]:
    """Suggestions about how the answer is written rather than which words it used."""
    improvements: list[str] = []

    if not writing.has_overview:
        improvements.append(
            "Open with an overview sentence: one line summarising the whole trend "
            "before the detail"
        )

    if writing.word_count < target_min:
        improvements.append(
            f"Write more: {writing.word_count} words is short for this task, which "
            f"expects {target_min}–{target_max}"
        )
    elif writing.word_count_score <= OVERLONG_FLOOR + 1:
        improvements.append(
            f"Tighten the answer: {writing.word_count} words is well past the "
            f"{target_min}–{target_max} the task expects"
        )

    if writing.lexical_diversity_score < WEAKNESS_THRESHOLD:
        improvements.append(
            "Vary the wording — several sentences reuse the same verb where a "
            "synonym would show range"
        )

    if writing.mean_sentence_length < SENTENCE_LENGTH_MIN and writing.sentence_count > 1:
        improvements.append(
            "Join some short sentences with 'which', 'while' or 'before' to build "
            "longer academic sentences"
        )

    return improvements


def _missing_grouped(detection: DetectionResult) -> list[tuple[str, list[TargetTerm], bool]]:
    """Missing required terms grouped by category, with whether it was used at all.

    Within a category, terms are ordered by ascending weight, so the suggestion
    names the most basic missing term rather than the most sophisticated one.
    Advice a struggling student cannot act on is not advice. Weight has no
    other effect on the result: the score itself is an unweighted count of
    unique terms, per FR-6.6.

    The third element records whether the student already used *something* from
    that category, which decides how the suggestion is phrased.
    """
    used_categories = {entry.term.category_code for entry in detection.detected}

    grouped: dict[str, tuple[str, list[TargetTerm]]] = {}
    for term in detection.missing:
        if not term.is_required:
            continue
        _, terms = grouped.setdefault(term.category_code, (term.category_name, []))
        terms.append(term)

    ordered = [
        (name, sorted(terms, key=lambda t: (t.weight, t.term)), code in used_categories)
        for code, (name, terms) in grouped.items()
    ]
    # An untouched category comes before one the student has already reached
    # into, and among equals the one with the most missing terms — the biggest
    # single gain available on the next attempt.
    ordered.sort(key=lambda row: (row[2], -len(row[1])))
    return ordered


def _missing_by_category(detection: DetectionResult) -> dict[str, list[str]]:
    """Required terms the student did not use, grouped by category.

    Bonus terms are excluded. They were never asked for, so listing them as
    things the student missed would report a failure that did not happen — and
    would not match the denominator the percentage was computed against. The
    full list, bonus terms included, is still persisted on the score's
    ``missing_terms`` column for research use.
    """
    missing: dict[str, list[str]] = {}
    for term in detection.missing:
        if not term.is_required:
            continue
        missing.setdefault(term.category_code, []).append(term.term)
    return {code: sorted(terms) for code, terms in sorted(missing.items())}


def _next_step(tier: RewardTier, graph_type: GraphType | None) -> str:
    step = NEXT_STEP_BY_TIER[tier]
    if graph_type is not None and tier in (RewardTier.FLOWER, RewardTier.STEADY):
        step = step.replace("another graph of this type", f"another {graph_type.value} graph")
        step = step.replace("the same chart", f"the same {graph_type.value} chart")
    return step
