"""unique leaderboard rows, and an orderable XP ledger

``uq_leaderboard_entry`` covers (scope, class_id, period_start, user_id), and
``class_id`` is NULL for every scope except ``class``. PostgreSQL treats NULLs
as distinct in a unique index, so that constraint enforces nothing at all for
the global, weekly and monthly boards: a period rebuilt twice concurrently left
every student ranked twice, silently, with no error to notice.

This adds the partial index that actually constrains them. Hand-written rather
than autogenerated — Alembic does not detect index-predicate changes, which is
precisely the kind of gap this migration exists to close.

It also switches ``xp_events.created_at`` from ``now()`` to
``clock_timestamp()``. ``now()`` is the transaction timestamp, so the four
entries one scoring can append — base award, high score bonus, streak bonus,
achievement reward — all shared a single value and the ledger's order fell back
to a random UUID. An append-only ledger that cannot be read back in the order
it was written is not much of a ledger.

Revision ID: 3192a974dff1
Revises: b9fcd0815bd5
Create Date: 2026-08-24 10:39:47.761831
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3192a974dff1"
down_revision: str | None = "b9fcd0815bd5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

INDEX_NAME = "uq_leaderboard_entry_unscoped"


def upgrade() -> None:
    # Any duplicates already on disk have to go first, or the index cannot be
    # built. The highest-numbered row of each duplicate group is dropped; they
    # are copies of one another, so which survives does not matter, and the
    # next rebuild replaces the period wholesale in any case.
    op.execute(
        sa.text(
            """
            DELETE FROM leaderboard_entries a
            USING leaderboard_entries b
            WHERE a.class_id IS NULL
              AND b.class_id IS NULL
              AND a.scope = b.scope
              AND a.period_start = b.period_start
              AND a.user_id = b.user_id
              AND a.id > b.id
            """
        )
    )
    op.create_index(
        INDEX_NAME,
        "leaderboard_entries",
        ["scope", "period_start", "user_id"],
        unique=True,
        postgresql_where=sa.text("class_id IS NULL"),
    )

    # Only the default changes; rows already written keep their timestamps.
    op.alter_column(
        "xp_events",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        existing_nullable=False,
        server_default=sa.text("clock_timestamp()"),
    )


def downgrade() -> None:
    op.alter_column(
        "xp_events",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        existing_nullable=False,
        server_default=sa.text("now()"),
    )
    op.drop_index(INDEX_NAME, table_name="leaderboard_entries")
