"""assignments, and the submission link

The join between a class and a graph that the schema never had. A teacher
could publish a graph and a student could find it, but nobody could *set* it —
so a section had a library where it needed a task list.

One table, and one nullable column on ``submissions``. Nothing existing is
altered and nothing is backfilled, so an old container and a new database
coexist through a rolling restart: every submission written before this
migration keeps ``assignment_id IS NULL``, which is exactly what free practice
looks like afterwards.

The column is nullable **by design**, not to spare a backfill. Practice a
student chose for themselves is the core loop, and it belongs to no
assignment; scoring, XP, tiers and the leaderboard read the same either way.

Three foreign keys, three different rules, because they answer three different
questions about what a delete may destroy:

* ``class_id`` CASCADEs — a deleted class takes its task list with it, the way
  it already takes its enrolments.
* ``graph_id`` RESTRICTs — a graph with work set against it must not vanish
  underneath the assignment, the same protection an attempted graph already
  has.
* ``assigned_by`` and ``submissions.assignment_id`` SET NULL — removing a
  teacher, or closing an assignment, must never delete a student's writing.
  The submission survives with its mark intact and simply stops naming the
  task it was done for.

``ix_assignments_class_open`` covers the only hot read there is: this class's
open work, soonest deadline first. There is deliberately no unique constraint
over ``(class_id, graph_id)`` — setting the same graph again next term is
legitimate.

Autogenerated, then read line by line: the ``ondelete`` clauses above are the
part Alembic gets from the model and the part a reviewer has to confirm,
because a wrong one here is only discovered on the day something is deleted.

Revision ID: 4ad10aa9a53f
Revises: 883a835f73c9
Create Date: 2026-08-27 02:12:19.439619
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "4ad10aa9a53f"
down_revision: str | None = "883a835f73c9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assignments",
        sa.Column("class_id", sa.Uuid(), nullable=False),
        sa.Column("graph_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("assigned_by", sa.Uuid(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["users.id"],
            name=op.f("fk_assignments_assigned_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["classes.id"],
            name=op.f("fk_assignments_class_id_classes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["graph_id"],
            ["graphs.id"],
            name=op.f("fk_assignments_graph_id_graphs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assignments")),
    )
    op.create_index(op.f("ix_assignments_class_id"), "assignments", ["class_id"], unique=False)
    op.create_index(
        "ix_assignments_class_open",
        "assignments",
        ["class_id", "is_active", "due_at"],
        unique=False,
    )
    op.create_index(op.f("ix_assignments_graph_id"), "assignments", ["graph_id"], unique=False)
    op.add_column("submissions", sa.Column("assignment_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_submissions_assignment_id"), "submissions", ["assignment_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_submissions_assignment_id_assignments"),
        "submissions",
        "assignments",
        ["assignment_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_submissions_assignment_id_assignments"), "submissions", type_="foreignkey"
    )
    op.drop_index(op.f("ix_submissions_assignment_id"), table_name="submissions")
    op.drop_column("submissions", "assignment_id")
    op.drop_index(op.f("ix_assignments_graph_id"), table_name="assignments")
    op.drop_index("ix_assignments_class_open", table_name="assignments")
    op.drop_index(op.f("ix_assignments_class_id"), table_name="assignments")
    op.drop_table("assignments")
    # ### end Alembic commands ###
