"""assessment details, issues and graph accuracy claims

The diagnostic record that sits beside a score without ever touching it. Three
tables, added; nothing existing is altered, so an old container and a new
database coexist safely through a rolling restart.

``assessment_issues`` is one table with a ``category`` discriminator rather
than one table per analyzer. Every analyzer produces the same eleven columns,
so a table each would repeat the schema four times, turn "this student's
issues in reading order" into a four-way union, and make "the mistakes this
class makes most" four queries instead of one ``GROUP BY``. The two indexes
serve those two opposite reads.

``graph_accuracy_claims`` stores correct claims as well as incorrect ones:
"you read four trends and got three right" is the educational figure, and it
cannot be recovered from the errors alone.

No backfill. Submissions scored before this existed keep no assessment rows —
re-running today's analyzers over yesterday's answers would stamp them with an
engine that did not exist when they were written, and mixing those into the
improvement trends would make the curves meaningless.

Autogenerated, then read line by line. The ``CHECK`` constraints below came
through because they are declared on tables being created; Alembic does not
detect a ``CHECK`` *changed* on an existing table, which is why every one of
them is generated from the Python enum rather than typed out.

Revision ID: 883a835f73c9
Revises: 5ed02bed82c4
Create Date: 2026-08-25 08:13:23.924043
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "883a835f73c9"
down_revision: str | None = "5ed02bed82c4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "assessment_details",
        sa.Column("submission_id", sa.Uuid(), nullable=False),
        sa.Column("assessment_version", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("grammar_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("spelling_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("sentence_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("word_usage_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("graph_accuracy_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("issue_count", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("suppressed_count", sa.Integer(), nullable=False),
        sa.Column(
            "truncated_categories",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "analyzer_status",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "analyzer_audiences",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'complete', 'partial')",
            name=op.f("ck_assessment_details_assessment_status_valid"),
        ),
        sa.CheckConstraint(
            "error_count <= issue_count", name=op.f("ck_assessment_details_errors_within_issues")
        ),
        sa.CheckConstraint(
            "grammar_score IS NULL OR (grammar_score >= 0 AND grammar_score <= 100)",
            name=op.f("ck_assessment_details_grammar_score_range"),
        ),
        sa.CheckConstraint(
            "graph_accuracy_score IS NULL OR (graph_accuracy_score >= 0 AND graph_accuracy_score <= 100)",
            name=op.f("ck_assessment_details_graph_accuracy_score_range"),
        ),
        sa.CheckConstraint(
            "issue_count >= 0 AND error_count >= 0 AND suppressed_count >= 0",
            name=op.f("ck_assessment_details_assessment_counts_non_negative"),
        ),
        sa.CheckConstraint(
            "sentence_score IS NULL OR (sentence_score >= 0 AND sentence_score <= 100)",
            name=op.f("ck_assessment_details_sentence_score_range"),
        ),
        sa.CheckConstraint(
            "spelling_score IS NULL OR (spelling_score >= 0 AND spelling_score <= 100)",
            name=op.f("ck_assessment_details_spelling_score_range"),
        ),
        sa.CheckConstraint(
            "word_usage_score IS NULL OR (word_usage_score >= 0 AND word_usage_score <= 100)",
            name=op.f("ck_assessment_details_word_usage_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submissions.id"],
            name=op.f("fk_assessment_details_submission_id_submissions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assessment_details")),
        sa.UniqueConstraint("submission_id", name=op.f("uq_assessment_details_submission_id")),
    )
    op.create_index("ix_assessment_details_status", "assessment_details", ["status"], unique=False)
    op.create_table(
        "assessment_issues",
        sa.Column("assessment_id", sa.Uuid(), nullable=False),
        sa.Column("category", sa.String(length=24), nullable=False),
        sa.Column("subtype", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("original_text", sa.Text(), nullable=False),
        sa.Column("suggested_text", sa.Text(), nullable=True),
        sa.Column("explanation", sa.String(length=400), nullable=False),
        sa.Column("start_index", sa.Integer(), nullable=False),
        sa.Column("end_index", sa.Integer(), nullable=False),
        sa.Column(
            "confidence",
            sa.Numeric(precision=4, scale=3),
            server_default=sa.text("1.000"),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "category IN ('grammar', 'spelling', 'sentence', 'word_usage', 'vocabulary', 'graph_accuracy', 'style')",
            name=op.f("ck_assessment_issues_issue_category_valid"),
        ),
        sa.CheckConstraint(
            "severity IN ('info', 'low', 'medium', 'high')",
            name=op.f("ck_assessment_issues_issue_severity_valid"),
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_assessment_issues_issue_confidence_range"),
        ),
        sa.CheckConstraint(
            "start_index >= 0 AND end_index >= start_index",
            name=op.f("ck_assessment_issues_issue_span_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessment_details.id"],
            name=op.f("fk_assessment_issues_assessment_id_assessment_details"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assessment_issues")),
    )
    op.create_index(
        "ix_assessment_issues_kind", "assessment_issues", ["category", "subtype"], unique=False
    )
    op.create_index(
        "ix_assessment_issues_reading_order",
        "assessment_issues",
        ["assessment_id", "start_index"],
        unique=False,
    )
    op.create_table(
        "graph_accuracy_claims",
        sa.Column("assessment_id", sa.Uuid(), nullable=False),
        sa.Column("claim_type", sa.String(length=24), nullable=False),
        sa.Column("series_label", sa.String(length=120), nullable=True),
        sa.Column("claimed", sa.String(length=120), nullable=False),
        sa.Column("actual", sa.String(length=120), nullable=False),
        sa.Column("verdict", sa.String(length=16), nullable=False),
        sa.Column(
            "confidence",
            sa.Numeric(precision=4, scale=3),
            server_default=sa.text("1.000"),
            nullable=False,
        ),
        sa.Column("start_index", sa.Integer(), nullable=False),
        sa.Column("end_index", sa.Integer(), nullable=False),
        sa.Column("issue_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "claim_type IN ('trend', 'peak', 'trough', 'comparison', 'magnitude', 'timing')",
            name=op.f("ck_graph_accuracy_claims_claim_type_valid"),
        ),
        sa.CheckConstraint(
            "issue_id IS NULL OR verdict = 'incorrect'",
            name=op.f("ck_graph_accuracy_claims_only_incorrect_claims_carry_an_issue"),
        ),
        sa.CheckConstraint(
            "verdict IN ('correct', 'incorrect', 'unverified')",
            name=op.f("ck_graph_accuracy_claims_claim_verdict_valid"),
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_graph_accuracy_claims_claim_confidence_range"),
        ),
        sa.CheckConstraint(
            "start_index >= 0 AND end_index >= start_index",
            name=op.f("ck_graph_accuracy_claims_claim_span_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessment_details.id"],
            name=op.f("fk_graph_accuracy_claims_assessment_id_assessment_details"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["issue_id"],
            ["assessment_issues.id"],
            name=op.f("fk_graph_accuracy_claims_issue_id_assessment_issues"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_graph_accuracy_claims")),
    )
    op.create_index(
        "ix_graph_accuracy_claims_assessment",
        "graph_accuracy_claims",
        ["assessment_id"],
        unique=False,
    )
    op.create_index(
        "ix_graph_accuracy_claims_outcome",
        "graph_accuracy_claims",
        ["verdict", "claim_type"],
        unique=False,
    )


def downgrade() -> None:
    """Drop all three. Nothing else refers to them, so nothing else breaks."""
    op.drop_index("ix_graph_accuracy_claims_outcome", table_name="graph_accuracy_claims")
    op.drop_index("ix_graph_accuracy_claims_assessment", table_name="graph_accuracy_claims")
    op.drop_table("graph_accuracy_claims")
    op.drop_index("ix_assessment_issues_reading_order", table_name="assessment_issues")
    op.drop_index("ix_assessment_issues_kind", table_name="assessment_issues")
    op.drop_table("assessment_issues")
    op.drop_index("ix_assessment_details_status", table_name="assessment_details")
    op.drop_table("assessment_details")
