"""initial schema

Revision ID: b9fcd0815bd5
Revises:
Create Date: 2026-08-23 09:05:39.663529
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "b9fcd0815bd5"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "achievements",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("icon", sa.String(length=32), nullable=False),
        sa.Column("xp_reward", sa.Integer(), nullable=False),
        sa.Column(
            "rule",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("xp_reward >= 0", name=op.f("ck_achievements_xp_reward_non_negative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_achievements")),
        sa.UniqueConstraint("code", name=op.f("uq_achievements_code")),
    )
    op.create_table(
        "avatars",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("gender", sa.String(length=16), nullable=False),
        sa.Column("image_url", sa.Text(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("unlock_level", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("gender IN ('male', 'female')", name=op.f("ck_avatars_gender_valid")),
        sa.CheckConstraint("unlock_level >= 1", name=op.f("ck_avatars_unlock_level_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_avatars")),
        sa.UniqueConstraint("code", name=op.f("uq_avatars_code")),
    )
    op.create_index("ix_avatars_gender", "avatars", ["gender"], unique=False)
    op.create_index(
        "uq_avatars_default_per_gender",
        "avatars",
        ["gender"],
        unique=True,
        postgresql_where=sa.text("is_default"),
        sqlite_where=sa.text("is_default"),
    )
    op.create_table(
        "badges",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("icon", sa.String(length=32), nullable=False),
        sa.Column("reward_tier", sa.String(length=16), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "reward_tier IN ('crown', 'flower', 'steady', 'hammer')",
            name=op.f("ck_badges_reward_tier_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_badges")),
        sa.UniqueConstraint("code", name=op.f("uq_badges_code")),
        sa.UniqueConstraint("reward_tier", name=op.f("uq_badges_reward_tier")),
    )
    op.create_table(
        "vocabulary_categories",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vocabulary_categories")),
        sa.UniqueConstraint("code", name=op.f("uq_vocabulary_categories_code")),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("gender", sa.String(length=16), nullable=False),
        sa.Column("avatar_id", sa.Uuid(), nullable=True),
        sa.Column("class_id", sa.Uuid(), nullable=True),
        sa.Column("total_xp", sa.BigInteger(), nullable=False),
        sa.Column("current_level", sa.Integer(), nullable=False),
        sa.Column("current_streak_days", sa.Integer(), nullable=False),
        sa.Column("longest_streak_days", sa.Integer(), nullable=False),
        sa.Column("last_activity_date", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("gender IN ('male', 'female')", name=op.f("ck_users_gender_valid")),
        sa.CheckConstraint(
            "role IN ('student', 'teacher', 'admin')", name=op.f("ck_users_role_valid")
        ),
        sa.CheckConstraint(
            "current_level >= 1 AND current_level <= 100", name=op.f("ck_users_level_range")
        ),
        sa.CheckConstraint(
            "current_streak_days >= 0", name=op.f("ck_users_current_streak_non_negative")
        ),
        sa.CheckConstraint(
            "longest_streak_days >= 0", name=op.f("ck_users_longest_streak_non_negative")
        ),
        sa.CheckConstraint("total_xp >= 0", name=op.f("ck_users_total_xp_non_negative")),
        sa.ForeignKeyConstraint(
            ["avatar_id"],
            ["avatars.id"],
            name=op.f("fk_users_avatar_id_avatars"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_index("ix_users_class_id", "users", ["class_id"], unique=False)
    op.create_index("ix_users_role", "users", ["role"], unique=False)
    op.create_index("ix_users_total_xp", "users", ["total_xp"], unique=False)
    op.create_table(
        "auth_sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("refresh_token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_auth_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_sessions")),
        sa.UniqueConstraint("refresh_token_hash", name=op.f("uq_auth_sessions_refresh_token_hash")),
    )
    op.create_index("ix_auth_sessions_expires_at", "auth_sessions", ["expires_at"], unique=False)
    op.create_index("ix_auth_sessions_user_id", "auth_sessions", ["user_id"], unique=False)
    op.create_table(
        "classes",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("teacher_id", sa.Uuid(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["users.id"],
            name=op.f("fk_classes_teacher_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_classes")),
        sa.UniqueConstraint("code", name=op.f("uq_classes_code")),
    )
    op.create_index("ix_classes_teacher_id", "classes", ["teacher_id"], unique=False)
    op.create_table(
        "graphs",
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("graph_type", sa.String(length=16), nullable=False),
        sa.Column("difficulty", sa.String(length=16), nullable=False),
        sa.Column(
            "chart_data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("reference_description", sa.Text(), nullable=True),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "difficulty IN ('beginner', 'intermediate', 'advanced')",
            name=op.f("ck_graphs_difficulty_valid"),
        ),
        sa.CheckConstraint(
            "graph_type IN ('line', 'bar', 'pie', 'area')", name=op.f("ck_graphs_graph_type_valid")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_graphs_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_graphs")),
    )
    op.create_index("ix_graphs_is_published", "graphs", ["is_published"], unique=False)
    op.create_index(
        "ix_graphs_type_difficulty", "graphs", ["graph_type", "difficulty"], unique=False
    )
    op.create_table(
        "vocabulary_items",
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("term", sa.String(length=100), nullable=False),
        sa.Column("lemma", sa.String(length=100), nullable=False),
        sa.Column("is_phrase", sa.Boolean(), nullable=False),
        sa.Column("weight", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("weight > 0", name=op.f("ck_vocabulary_items_weight_positive")),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["vocabulary_categories.id"],
            name=op.f("fk_vocabulary_items_category_id_vocabulary_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_vocabulary_items_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vocabulary_items")),
        sa.UniqueConstraint("lemma", name=op.f("uq_vocabulary_items_lemma")),
    )
    op.create_index(
        "ix_vocabulary_items_category_id", "vocabulary_items", ["category_id"], unique=False
    )
    op.create_index(
        "ix_vocabulary_items_is_active", "vocabulary_items", ["is_active"], unique=False
    )
    op.create_table(
        "analytics_snapshots",
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column("class_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column(
            "metrics",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "scope IN ('platform', 'class', 'student')",
            name=op.f("ck_analytics_snapshots_scope_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["classes.id"],
            name=op.f("fk_analytics_snapshots_class_id_classes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_analytics_snapshots_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analytics_snapshots")),
        sa.UniqueConstraint(
            "scope", "class_id", "user_id", "period_start", name="uq_analytics_snapshot"
        ),
    )
    op.create_index(
        "ix_analytics_snapshots_scope_period",
        "analytics_snapshots",
        ["scope", "period_start"],
        unique=False,
    )
    op.create_table(
        "graph_target_vocabulary",
        sa.Column("graph_id", sa.Uuid(), nullable=False),
        sa.Column("vocabulary_item_id", sa.Uuid(), nullable=False),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["graph_id"],
            ["graphs.id"],
            name=op.f("fk_graph_target_vocabulary_graph_id_graphs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vocabulary_item_id"],
            ["vocabulary_items.id"],
            name=op.f("fk_graph_target_vocabulary_vocabulary_item_id_vocabulary_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_graph_target_vocabulary")),
        sa.UniqueConstraint("graph_id", "vocabulary_item_id", name="uq_graph_vocabulary"),
    )
    op.create_index(
        "ix_graph_target_vocabulary_graph_id", "graph_target_vocabulary", ["graph_id"], unique=False
    )
    op.create_table(
        "leaderboard_entries",
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column("class_id", sa.Uuid(), nullable=True),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("xp", sa.BigInteger(), nullable=False),
        sa.Column("average_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("submission_count", sa.Integer(), nullable=False),
        sa.Column("achievement_count", sa.Integer(), nullable=False),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "(scope = 'class' AND class_id IS NOT NULL) OR (scope <> 'class' AND class_id IS NULL)",
            name=op.f("ck_leaderboard_entries_class_scope_consistent"),
        ),
        sa.CheckConstraint(
            "scope IN ('global', 'class', 'weekly', 'monthly')",
            name=op.f("ck_leaderboard_entries_scope_valid"),
        ),
        sa.CheckConstraint("rank >= 1", name=op.f("ck_leaderboard_entries_rank_positive")),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["classes.id"],
            name=op.f("fk_leaderboard_entries_class_id_classes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_leaderboard_entries_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_leaderboard_entries")),
        sa.UniqueConstraint(
            "scope", "class_id", "period_start", "user_id", name="uq_leaderboard_entry"
        ),
    )
    op.create_index(
        "ix_leaderboard_lookup",
        "leaderboard_entries",
        ["scope", "class_id", "period_start", "rank"],
        unique=False,
    )
    op.create_table(
        "submissions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("graph_id", sa.Uuid(), nullable=False),
        sa.Column("input_method", sa.String(length=16), nullable=False),
        sa.Column("answer_text", sa.Text(), nullable=True),
        sa.Column("original_image_path", sa.Text(), nullable=True),
        sa.Column("ocr_text", sa.Text(), nullable=True),
        sa.Column("ocr_provider", sa.String(length=32), nullable=True),
        sa.Column("ocr_confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column(
            "ocr_blocks",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("was_ocr_edited", sa.Boolean(), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("scored_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "input_method IN ('typed', 'handwriting')",
            name=op.f("ck_submissions_input_method_valid"),
        ),
        sa.CheckConstraint(
            "ocr_provider IS NULL OR ocr_provider IN ('google_vision', 'easyocr', 'tesseract')",
            name=op.f("ck_submissions_ocr_provider_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'extracting', 'extracted', 'analyzing', 'scored', 'failed')",
            name=op.f("ck_submissions_status_valid"),
        ),
        sa.CheckConstraint(
            "ocr_confidence IS NULL OR (ocr_confidence >= 0 AND ocr_confidence <= 1)",
            name=op.f("ck_submissions_ocr_confidence_range"),
        ),
        sa.CheckConstraint("word_count >= 0", name=op.f("ck_submissions_word_count_non_negative")),
        sa.ForeignKeyConstraint(
            ["graph_id"],
            ["graphs.id"],
            name=op.f("fk_submissions_graph_id_graphs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_submissions_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_submissions")),
    )
    op.create_index("ix_submissions_graph_id", "submissions", ["graph_id"], unique=False)
    op.create_index("ix_submissions_status", "submissions", ["status"], unique=False)
    op.create_index(
        "ix_submissions_user_submitted", "submissions", ["user_id", "submitted_at"], unique=False
    )
    op.create_table(
        "teacher_reports",
        sa.Column("teacher_id", sa.Uuid(), nullable=False),
        sa.Column("class_id", sa.Uuid(), nullable=True),
        sa.Column("report_type", sa.String(length=32), nullable=False),
        sa.Column("format", sa.String(length=8), nullable=False),
        sa.Column(
            "parameters",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("file_path", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "format IN ('csv', 'xlsx', 'pdf')", name=op.f("ck_teacher_reports_format_valid")
        ),
        sa.CheckConstraint(
            "report_type IN ('class_summary', 'student_detail', 'vocabulary_usage', 'submission_export')",
            name=op.f("ck_teacher_reports_report_type_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'ready', 'failed')", name=op.f("ck_teacher_reports_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["classes.id"],
            name=op.f("fk_teacher_reports_class_id_classes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["users.id"],
            name=op.f("fk_teacher_reports_teacher_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teacher_reports")),
    )
    op.create_index(
        "ix_teacher_reports_teacher_created",
        "teacher_reports",
        ["teacher_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "scores",
        sa.Column("submission_id", sa.Uuid(), nullable=False),
        sa.Column("vocabulary_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("writing_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("final_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("vocabulary_percentage", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("detected_count", sa.Integer(), nullable=False),
        sa.Column("unique_detected_count", sa.Integer(), nullable=False),
        sa.Column("total_target_count", sa.Integer(), nullable=False),
        sa.Column(
            "detected_terms",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "missing_terms",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "category_breakdown",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "writing_breakdown",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("reward_tier", sa.String(length=16), nullable=False),
        sa.Column(
            "feedback",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("engine_version", sa.String(length=32), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "reward_tier IN ('crown', 'flower', 'steady', 'hammer')",
            name=op.f("ck_scores_reward_tier_valid"),
        ),
        sa.CheckConstraint(
            "final_score >= 0 AND final_score <= 100", name=op.f("ck_scores_final_score_range")
        ),
        sa.CheckConstraint(
            "total_target_count >= 0", name=op.f("ck_scores_total_target_non_negative")
        ),
        sa.CheckConstraint(
            "vocabulary_score >= 0 AND vocabulary_score <= 100",
            name=op.f("ck_scores_vocabulary_score_range"),
        ),
        sa.CheckConstraint(
            "writing_score >= 0 AND writing_score <= 100",
            name=op.f("ck_scores_writing_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submissions.id"],
            name=op.f("fk_scores_submission_id_submissions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scores")),
        sa.UniqueConstraint("submission_id", name=op.f("uq_scores_submission_id")),
    )
    op.create_index("ix_scores_final_score", "scores", ["final_score"], unique=False)
    op.create_index("ix_scores_reward_tier", "scores", ["reward_tier"], unique=False)
    op.create_table(
        "user_achievements",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("achievement_id", sa.Uuid(), nullable=False),
        sa.Column("submission_id", sa.Uuid(), nullable=True),
        sa.Column(
            "unlocked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["achievement_id"],
            ["achievements.id"],
            name=op.f("fk_user_achievements_achievement_id_achievements"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submissions.id"],
            name=op.f("fk_user_achievements_submission_id_submissions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_achievements_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_achievements")),
        sa.UniqueConstraint("user_id", "achievement_id", name="uq_user_achievement"),
    )
    op.create_index("ix_user_achievements_user_id", "user_achievements", ["user_id"], unique=False)
    op.create_table(
        "user_badges",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("badge_id", sa.Uuid(), nullable=False),
        sa.Column("submission_id", sa.Uuid(), nullable=False),
        sa.Column(
            "awarded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["badge_id"],
            ["badges.id"],
            name=op.f("fk_user_badges_badge_id_badges"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submissions.id"],
            name=op.f("fk_user_badges_submission_id_submissions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_badges_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_badges")),
        sa.UniqueConstraint("submission_id", name=op.f("uq_user_badges_submission_id")),
    )
    op.create_index(
        "ix_user_badges_user_awarded", "user_badges", ["user_id", "awarded_at"], unique=False
    )
    op.create_table(
        "xp_events",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=32), nullable=False),
        sa.Column("submission_id", sa.Uuid(), nullable=True),
        sa.Column("achievement_id", sa.Uuid(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("event_date", sa.Date(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "reason IN ('submission', 'high_score_bonus', 'streak_bonus', 'achievement', 'manual_adjustment')",
            name=op.f("ck_xp_events_reason_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["achievement_id"],
            ["achievements.id"],
            name=op.f("fk_xp_events_achievement_id_achievements"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submissions.id"],
            name=op.f("fk_xp_events_submission_id_submissions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_xp_events_user_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_xp_events")),
    )
    op.create_index("ix_xp_events_reason", "xp_events", ["reason"], unique=False)
    op.create_index(
        "ix_xp_events_user_created", "xp_events", ["user_id", "created_at"], unique=False
    )
    op.create_index(
        "uq_xp_events_streak_daily",
        "xp_events",
        ["user_id", "event_date"],
        unique=True,
        postgresql_where=sa.text("reason = 'streak_bonus'"),
        sqlite_where=sa.text("reason = 'streak_bonus'"),
    )
    # users.class_id and classes.teacher_id reference each other, so neither
    # table can carry its constraint at CREATE TABLE time. This is added after
    # both exist. Alembic's autogenerate does not emit it — the model marks the
    # foreign key use_alter, which drops it from CREATE TABLE without producing
    # a replacement statement.
    op.create_foreign_key(
        "fk_users_class_id_classes",
        "users",
        "classes",
        ["class_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_constraint("fk_users_class_id_classes", "users", type_="foreignkey")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_xp_events_streak_daily",
        table_name="xp_events",
        postgresql_where=sa.text("reason = 'streak_bonus'"),
        sqlite_where=sa.text("reason = 'streak_bonus'"),
    )
    op.drop_index("ix_xp_events_user_created", table_name="xp_events")
    op.drop_index("ix_xp_events_reason", table_name="xp_events")
    op.drop_table("xp_events")
    op.drop_index("ix_user_badges_user_awarded", table_name="user_badges")
    op.drop_table("user_badges")
    op.drop_index("ix_user_achievements_user_id", table_name="user_achievements")
    op.drop_table("user_achievements")
    op.drop_index("ix_scores_reward_tier", table_name="scores")
    op.drop_index("ix_scores_final_score", table_name="scores")
    op.drop_table("scores")
    op.drop_index("ix_teacher_reports_teacher_created", table_name="teacher_reports")
    op.drop_table("teacher_reports")
    op.drop_index("ix_submissions_user_submitted", table_name="submissions")
    op.drop_index("ix_submissions_status", table_name="submissions")
    op.drop_index("ix_submissions_graph_id", table_name="submissions")
    op.drop_table("submissions")
    op.drop_index("ix_leaderboard_lookup", table_name="leaderboard_entries")
    op.drop_table("leaderboard_entries")
    op.drop_index("ix_graph_target_vocabulary_graph_id", table_name="graph_target_vocabulary")
    op.drop_table("graph_target_vocabulary")
    op.drop_index("ix_analytics_snapshots_scope_period", table_name="analytics_snapshots")
    op.drop_table("analytics_snapshots")
    op.drop_index("ix_vocabulary_items_is_active", table_name="vocabulary_items")
    op.drop_index("ix_vocabulary_items_category_id", table_name="vocabulary_items")
    op.drop_table("vocabulary_items")
    op.drop_index("ix_graphs_type_difficulty", table_name="graphs")
    op.drop_index("ix_graphs_is_published", table_name="graphs")
    op.drop_table("graphs")
    op.drop_index("ix_classes_teacher_id", table_name="classes")
    op.drop_table("classes")
    op.drop_index("ix_auth_sessions_user_id", table_name="auth_sessions")
    op.drop_index("ix_auth_sessions_expires_at", table_name="auth_sessions")
    op.drop_table("auth_sessions")
    op.drop_index("ix_users_total_xp", table_name="users")
    op.drop_index("ix_users_role", table_name="users")
    op.drop_index("ix_users_class_id", table_name="users")
    op.drop_table("users")
    op.drop_table("vocabulary_categories")
    op.drop_table("badges")
    op.drop_index(
        "uq_avatars_default_per_gender",
        table_name="avatars",
        postgresql_where=sa.text("is_default"),
        sqlite_where=sa.text("is_default"),
    )
    op.drop_index("ix_avatars_gender", table_name="avatars")
    op.drop_table("avatars")
    op.drop_table("achievements")
    # ### end Alembic commands ###
